Float format
bird-house/finch pull request #271
Opened 2023-01-24 18:11 UTC by perronld

## Overview

This PR fixes #263

Changes:

* Manually convert values to string using formatting instead of round() when csv_precision is requested

2023-01-24 18:21 UTC, aulemahal approved these changes
Looks good indeed!

2023-01-24 18:37 UTC, aulemahal approved these changes
I missed a breaking detail!

2023-01-24 18:37 UTC, aulemahal requested changes
(woups my second review meant to be "request changes", so here's a 3rd :sweat: )

2023-01-24 20:48 UTC, perronld commented on finch/processes/ensemble_utils.py
> -        df.dropna().to_csv(ensemble_csv)
Yes, I got a request to keep those lines here: https://ccdpwiki.atlassian.net/browse/CLIM-287

2023-02-03 16:10 UTC, aulemahal approved these changes

2023-02-03 16:10 UTC, merged